#:schema node_modules/wrangler/config-schema.json
name = "gapfind-cf-gateway"
main = "src/index.ts"
compatibility_date = "2024-05-02"
compatibility_flags = ["nodejs_compat"]

[vars]
ALLOWED_ORIGIN = "https://gapfind.pages.dev"
GENERIC_RPM = 20

[triggers]
crons = ["*/1 * * * *"]